import { Network } from "alchemy-sdk";
import { abi as escrowV2Abi } from "../escrowV2.json";
import { abi as monadEscrowV2Abi } from "../monadEscrowV2.json";

export const BATCH_SIZE = 500;

const isProd = Bun.env.NODE_ENV === "production";
export const UPDATE_INTERVAL_MS = isProd ? 24 * 60 * 60 * 1000 : 1 * 60 * 1000;
export const LOG_INTERVAL_MS = 60 * 60 * 1000; // 1 hour
export const NULL_ADDRESS = "0x0000000000000000000000000000000000000000";
export const YAP_API_URL = Bun.env.YAP_API_URL;
export const YAP_API_KEY = Bun.env.YAP_API_KEY;
export const BASE_CONTRACT_ADDRESS = Bun.env.BASE_ESCROW_CONTRACT;
export const MONAD_ESCROW_CONTRACT = Bun.env.MONAD_ESCROW_CONTRACT;

export const ECOSYSTEM_DETAILS = [
  {
    chainId: 84532,
    ecosystem: "base_sepolia",
    escrowContract: BASE_CONTRACT_ADDRESS,
    network: Network.BASE_SEPOLIA,
    apiKey: Bun.env.ALCHEMY_BASE_SEPOLIA_KEY,
    rpcUrl: Bun.env.BASE_SEPOLIA_PROVIDER_URL,
    wsUrl: Bun.env.BASE_SEPOLIA_WS_PROVIDER_URL,
    env: "development",
    forActiveListener: true,
    abi: escrowV2Abi,
  },
  {
    chainId: 8453,
    ecosystem: "base_mainnet",
    escrowContract: BASE_CONTRACT_ADDRESS,
    network: Network.BASE_MAINNET,
    apiKey: Bun.env.ALCHEMY_BASE_MAINNET_KEY,
    rpcUrl: Bun.env.BASE_MAINNET_PROVIDER_URL,
    wsUrl: Bun.env.BASE_MAINNET_WS_PROVIDER_URL,
    env: "prod",
    forActiveListener: true,
    abi: escrowV2Abi,
  },
  {
    chainId: 10143,
    ecosystem: "monad_testnet",
    escrowContract: MONAD_ESCROW_CONTRACT,
    network: Network.MONAD_TESTNET,
    apiKey: Bun.env.ALCHEMY_MONAD_TESTNET_KEY,
    rpcUrl: Bun.env.MONAD_PROVIDER_URL,
    wsUrl: Bun.env.MONAD_WS_PROVIDER_URL,
    env: "development",
    forActiveListener: true,
    abi: monadEscrowV2Abi,
  },
  {
    chainId: 143,
    ecosystem: "monad_mainnet",
    escrowContract: MONAD_ESCROW_CONTRACT,
    network: Network.MONAD_TESTNET, // TODO: change when details are added to ethers
    apiKey: Bun.env.ALCHEMY_MONAD_TESTNET_KEY,
    rpcUrl: Bun.env.MONAD_PROVIDER_URL,
    wsUrl: Bun.env.MONAD_WS_PROVIDER_URL,
    env: "prod",
    forActiveListener: false,
    abi: monadEscrowV2Abi,
  },
  {
    chainId: 1,
    ecosystem: "ethereum_mainnet",
    escrowContract: NULL_ADDRESS,
    network: Network.ETH_MAINNET,
    apiKey: Bun.env.ALCHEMY_API_KEY,
    rpcUrl: Bun.env.ETHEREUM_PROVIDER_URL,
    wsUrl: Bun.env.ETHEREUM_WS_PROVIDER_URL,
    env: "prod",
    forActiveListener: false,
    abi: escrowV2Abi,
  },
  {
    chainId: 11155111,
    ecosystem: "ethereum_sepolia",
    escrowContract: NULL_ADDRESS,
    network: Network.ETH_SEPOLIA,
    apiKey: Bun.env.ALCHEMY_API_KEY,
    rpcUrl: Bun.env.ETHEREUM_SEPOLIA_PROVIDER_URL,
    wsUrl: Bun.env.ETHEREUM_SEPOLIA_WS_PROVIDER_URL,
    env: "development",
    forActiveListener: false,
    abi: escrowV2Abi,
  },
  {
    chainId: 10,
    ecosystem: "opt_mainnet",
    escrowContract: NULL_ADDRESS,
    network: Network.OPT_MAINNET,
    apiKey: Bun.env.ALCHEMY_API_KEY,
    rpcUrl: Bun.env.OPT_MAINNET_PROVIDER_URL,
    wsUrl: Bun.env.OPT_MAINNET_WS_PROVIDER_URL,
    env: "prod",
    forActiveListener: false,
    abi: escrowV2Abi,
  },
  {
    chainId: 11155420,
    ecosystem: "opt_sepolia",
    escrowContract: NULL_ADDRESS,
    network: Network.OPT_SEPOLIA,
    apiKey: Bun.env.ALCHEMY_API_KEY,
    rpcUrl: Bun.env.OPT_SEPOLIA_PROVIDER_URL,
    wsUrl: Bun.env.OPT_SEPOLIA_WS_PROVIDER_URL,
    env: "development",
    forActiveListener: false,
    abi: escrowV2Abi,
  },
  {
    chainId: 42161,
    ecosystem: "arbitrum_mainnet",
    escrowContract: NULL_ADDRESS,
    network: Network.ARB_MAINNET,
    apiKey: Bun.env.ALCHEMY_API_KEY,
    rpcUrl: Bun.env.ARB_MAINNET_PROVIDER_URL,
    wsUrl: Bun.env.ARB_MAINNET_WS_PROVIDER_URL,
    env: "prod",
    forActiveListener: false,
    abi: escrowV2Abi,
  },
  {
    chainId: 421614,
    ecosystem: "arb_sepolia",
    escrowContract: NULL_ADDRESS,
    network: Network.ARB_SEPOLIA,
    apiKey: Bun.env.ALCHEMY_API_KEY,
    rpcUrl: Bun.env.ARB_SEPOLIA_PROVIDER_URL,
    wsUrl: Bun.env.ARB_SEPOLIA_WS_PROVIDER_URL,
    env: "development",
    forActiveListener: false,
    abi: escrowV2Abi,
  },
  {
    chainId: 56,
    ecosystem: "bnb_mainnet",
    escrowContract: NULL_ADDRESS,
    network: Network.BNB_MAINNET,
    apiKey: Bun.env.ALCHEMY_API_KEY,
    rpcUrl: Bun.env.BNB_MAINNET_PROVIDER_URL,
    wsUrl: Bun.env.BNB_MAINNET_WS_PROVIDER_URL,
    env: "prod",
    forActiveListener: false,
    abi: escrowV2Abi,
  },
  {
    chainId: 97,
    ecosystem: "bnb_testnet",
    escrowContract: NULL_ADDRESS,
    network: Network.BNB_TESTNET,
    apiKey: Bun.env.ALCHEMY_API_KEY,
    rpcUrl: Bun.env.BNB_TESTNET_PROVIDER_URL,
    wsUrl: Bun.env.BNB_TESTNET_WS_PROVIDER_URL,
    env: "development",
    forActiveListener: false,
    abi: escrowV2Abi,
  },
];
